import Product from "../product/product"
import SectionMenu from "./sectionMenu"
import CustomCarousal from "../carousal/carousel"
import CustomCardSlider from "../cardSlider/cardSlider"

import ProductImage1 from "@/public/product.jpeg"
import ProductImage2 from "@/public/camera.png"
import ProductImage3 from "@/public/login.jpeg"

const HomeComponent = () => {

  const carousalData = [
    {
      image: ProductImage1,
      text: "First Image Lorem ipsum dolor sit amet consectetur adipisicing elit."
    },
    {
      image: ProductImage2,
      text: "second Image Lorem ipsum dolor sit amet consectetur adipisicing elit."
    },
    {
      image: ProductImage3,
      text: "Third Image Lorem ipsum dolor sit amet consectetur adipisicing elit."
    },
  ]
  const cardData = [
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage1,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
    {
      productImage: ProductImage2,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,
    },
    {
      productImage: ProductImage3,
      productName: "First Image Lorem ipsum dolor ",
      productMRP: 465,
      productPrice: 405,
      productDicount: 45,
      productRating:4,
      productStarCount:20,

    },
  ]

  return (
    <>
      <div className="flex flex-row">
        <SectionMenu />
        <CustomCarousal className="" carousalItems={carousalData} />
      </div>
      <div>
        <CustomCardSlider cardItems={cardData}></CustomCardSlider>
      </div>
      <Product>

      </Product>
    </>
  )
}

export default HomeComponent